Develop
Sunkerus/java-filmorate pull request #1
Opened 2023-03-21 18:47 UTC by Sunkerus

Александр, привет!

**Все изменения внесенные описали в файле readme.**

Выполнен откат ветки main до соотвествия тз 11.2 спринта,  проверенные ревьювером Рустема. 
Добавлена актуальная схема базы данных.

Репозиторий был перенесен в мой git для наибольшей корректности условию выполняемого задания.

2023-03-22 21:35 UTC, alexache requested changes

2023-03-22 21:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +            "WHERE fl.film_id IN (SELECT film_id FROM like_to_film WHERE user_id = ?) " +
Влоэенные запросы не очень хорошая идея, лучше бы попытаться написать через джоины

2023-03-22 21:35 UTC, alexache commented on README.md
> +`GET /films/common?userId={userId}&friendId={friendId}`
Похоже на копипаст описания прошлой функциональности

2023-03-22 21:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +       // LocalDate dateTime = LocalDate.ofEpochDay(event.getTimestamp());
закомментированный код лучше удалять

2023-03-22 21:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Optional<Long> idBig = recommendationDao.getIdBig(id);
Не очень хорошее имя переменной - что значит big?

2023-03-22 21:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/RecommendationDaoImpl.java
> +                .findFirst();
Почему только первый?

2023-03-22 21:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/RecommendationDaoImpl.java
> +    public Optional<Long> getIdBig(long id) {
Хорошо бы более понятно название метода

2023-03-22 21:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            for (Long aLong : bigListIdFilm) {
Почему бы не написать тоже самое только одним запросом - найти лайкнутые другими пользователями фильмы, который текующий пользователь не лайкал?

2023-03-22 21:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                resultFilm.add(filmStorage.findFilmById(aLong));
Лучше заменить на запрос получения списка фильмов по списку айди - и не через  вызов в цикле той же операции получения фильма по айди, а полноценный другой запрос к базе

2023-03-22 21:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
>          Mpa mpa = mpaRating.getMpaById(resultSet.getInt("mpa_rating"));
Не должно быть обращений к другим дао для получения доп полей фильма - их можно получать через джоинутый запрос к базе без дополнительных обращений.
С жанрами немного сложнее, но тоже нельзя допускать запросов к базе в цикле - то есть наполнение жанрами должно происходить по списку фильмов, а не в цикле на каждый фильм

2023-03-22 21:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
>          Set<Long> likes = likesDao.findLikesByFilm(resultSet.getLong("film_id"));
И это через джоин

2023-03-22 21:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        Set<Director> directors = new HashSet<>(filmDirectorDao.getDirectorByFilm(resultSet.getLong("film_id")));
И это через джоин

2023-03-23 14:22 UTC, MaxiBit1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Optional<Long> idBig = recommendationDao.getIdBig(id);
Исправлено

2023-03-23 14:25 UTC, MaxiBit1 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/RecommendationDaoImpl.java
> +                .findFirst();
Здесь у нас находится айди пользователя с максимальным колличеством пересечений по лайкам

2023-03-23 14:25 UTC, MaxiBit1 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/RecommendationDaoImpl.java
> +    public Optional<Long> getIdBig(long id) {
Исправлено

2023-03-23 14:26 UTC, MaxiBit1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                resultFilm.add(filmStorage.findFilmById(aLong));
Исправлено

2023-03-23 17:14 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDao.java
> +    List<Review> findALLReviews(Integer limit);
Исправил

2023-03-23 17:20 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        return findById(review.getReviewId());
Исправил

2023-03-23 17:21 UTC, Sunkerus commented on README.md
> +`GET /fimls/search`
Исправил

2023-03-23 17:37 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        if (by.contains("director") && by.contains("title")) {
Исправил

2023-03-23 17:38 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +            log.debug("Инициализирован поиск фильмов по названию и по режессеру.");
Исправил

2023-03-23 17:39 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +       // LocalDate dateTime = LocalDate.ofEpochDay(event.getTimestamp());
Исправлено

2023-03-23 18:59 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
>          Set<Long> likes = likesDao.findLikesByFilm(resultSet.getLong("film_id"));
Исправлено

2023-03-23 19:13 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +            "WHERE fl.film_id IN (SELECT film_id FROM like_to_film WHERE user_id = ?) " +
Исправлено

2023-03-25 12:23 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        if (by.contains("director") && by.contains("title")) {
Исправлено

2023-03-25 13:15 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        return findById(review.getReviewId());
Поиск осуществляется для получения актуальных данных из базы.
Если выводить информацию о переданном объекте, то тесты не получают информацию о userId и filmId.

2023-03-25 17:15 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
>          Mpa mpa = mpaRating.getMpaById(resultSet.getInt("mpa_rating"));
исправлено

2023-03-26 18:55 UTC, alexache approved these changes

2023-03-26 18:55 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/RecommendationDaoImpl.java
> +    public List<Film> getListFilm(List<Long> idFilms) {
(опционально) И по содержимому, и по смыслу - этот метод логичнее иметь в FilmDbStorage, здесь ведь уже ничего нет про сами лайки

2023-03-26 18:55 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDirectorDaoImpl.java
> +        int check = jdbcTemplate.update(SQL_INSERT_FILM_DIRECTOR, filmId, directorId);
(опционально) Для чего сохранять результат и ничего не делать?

2023-04-02 11:04 UTC, merged