Controllers films users
Sunkerus/java-filmorate pull request #7
Opened 2023-03-05 22:41 UTC by Sunkerus

2023-03-05 22:47 UTC, Sunkerus commented
Добавил структуру, для дальнейшей модернизации приложения.

А именно:

**- Контроллер

Ошибки
Модель данных
Валидатор
Тесты**

2023-03-06 16:49 UTC, alexache requested changes

2023-03-06 16:49 UTC, alexache commented on pom.xml
> +		<dependency>
(опционально) тестовые зависимости лучше писать в конце списка зависимостей

2023-03-06 16:49 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Integer, Film> filmStorage = new HashMap<>();
Лучше писать интерфейс вместо конкретной реалзации в типе поля/аргументов

2023-03-06 16:49 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film postFilms(@Valid @NotNull @RequestBody Film film) throws ValidationException {
почему postFIlms во множественном числе? Это ведь метод создания одного фильма

2023-03-06 16:49 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else {throw new ValidationException("Пользователь с таким id не найден. ");}
Переносы строк все же должны быть

2023-03-06 22:48 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/validate/Validator.java
> +                            user.setName(user.getLogin());
Изменил название на более корректное, а также убрал повторяющиеся методы валидации. 

Все необходимые методы вынес в аннотации в model.Film & model.User с помощью javax, как указано в ТЗ.

2023-03-06 22:49 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/validate/Validator.java
> +        if (film != null ) {
Удалил повторяющиеся проверки, а также вынес возможные варианты проверок в аннотации.

2023-03-06 22:58 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else {throw new ValidationException("Пользователь с таким id не найден. ");}
Исправил.
Также проверил стиль оформления всего кода, добавил изменения в последнем коммите.

2023-03-06 22:59 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film postFilms(@Valid @NotNull @RequestBody Film film) throws ValidationException {
Исправил и обновил названия методов, как для фильмов, так для пользователей, теперь всё должно быть корректно.

2023-03-06 22:59 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Integer, Film> filmStorage = new HashMap<>();
Исправил.

2023-03-06 23:04 UTC, Sunkerus commented on pom.xml
> +		<dependency>
Исправил.
Зависимости перенес в конец файла.

2023-03-07 19:31 UTC, alexache approved these changes

2023-03-07 19:31 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/validate/FilmValidator.java
> +        validateDescription(film);
Эти 2 валидации тоже можно покрыть аннотациями - 
@Size(max = 200, message = "Описание ..."), с датой навскидку не помню, но тоже должно быть

2023-03-07 19:31 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/validate/UserValidator.java
> +        if (user.getBirthday().isAfter(LocalDate.now())) {
@Past ?

2023-03-08 14:59 UTC, merged