add: sprint10
Sunkerus/java-filmorate pull request #8
Opened 2023-03-10 13:03 UTC by Sunkerus

2023-03-11 08:22 UTC, alexache requested changes

2023-03-11 08:22 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -        log.trace("Был запрошен список фильмов");
Логгирование можно было оставлять

2023-03-11 08:22 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        boolean isFilmExist = films.values().stream().anyMatch(f -> f.equals(film));
У сохраненный фильмов есть айди, у новых нет, то есть эта проверка не делает ничего полезного

2023-03-11 08:22 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            Film deleteFilm = films.get(id);
Для чего столько операций? почему не просто return films.remove(id) ?

2023-03-11 08:22 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        boolean isUserExist = users.values().stream().anyMatch(u -> u.equals(user));
Похожие вопросы, как и в сторадже фильмов

2023-03-11 08:22 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            userStorage.add(user);
Зачем это дублирование кода? Ниже такой же код

2023-03-11 08:28 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -        log.trace("Был запрошен список фильмов");
Я подумал, что будет более корректно переместить логирование в класс FilmService и добавить вызов log у каждой фукнции.

2023-03-11 08:54 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            Film deleteFilm = films.get(id);
Исправил, добавил дополнительную проверку при удалении на получение null

2023-03-11 08:57 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            userStorage.add(user);
Исправил

2023-03-11 09:09 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        boolean isFilmExist = films.values().stream().anyMatch(f -> f.equals(film));
Исправил, удалил лишнюю логику.

2023-03-11 09:12 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        boolean isUserExist = users.values().stream().anyMatch(u -> u.equals(user));
Исправил, удалил лишнюю логику.

2023-03-12 07:02 UTC, alexache approved these changes

2023-03-12 07:02 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        Film deleteFilm = films.remove(id);
Точно так же выглядит метод в InMemoryUserStorage - я и имел в виду, что по аналогии с комментариями в сторадже фильмов, нужно внести правки в сторадже юзеров. То есть там тоже стоит убрать лишние вызовы при удалении

2023-03-13 11:50 UTC, merged