refactor:sprint11_2
Sunkerus/java-filmorate pull request #9
Opened 2023-03-14 06:10 UTC by Sunkerus

2023-03-14 10:24 UTC, alexache requested changes

2023-03-14 10:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.containsFilm(id)) {
То есть теперь никак не отслеживается какой юзер какому фильму поставил лайк? Как тогда проверять, что дизлайк валиден? Не помешает вспомогательная таблица для хранения этой связи?

2023-03-14 10:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "UPDATE FILMS SET RATE=RATE-5 WHERE id = ?";
Почему 5?

2023-03-14 10:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.getGenres().forEach(genre -> jdbcTemplate.update(sqlGenre, filmId, genre.getId()));
Запрос к базе  в цикле - очень плохая практика, Нужно сделать batch insert

2023-03-14 10:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.getGenres().forEach(
Тот же коммент про батч операцию. Так же можно вынести такую общую часть в отдельный метод, чтобы не повторяться

2023-03-14 10:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/genre/GenreDbStorage.java
> +    public void add(String genre) {
Для чего этот метод и почему он публичный, но не в интерфейсе?

2023-03-14 10:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/mpa/MpaDbStorage.java
> +    public void add(String mpa) {
Такой же вопрос

2023-03-14 10:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        if (user.getName() == null || user.getName().isBlank()) {
(опционально) Не уверен, что это нужно в сторадже, может раньше?

2023-03-14 10:24 UTC, alexache commented on src/main/resources/schema.sql
> +    description  varchar(100),
Как-то мало

2023-03-14 14:42 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "UPDATE FILMS SET RATE=RATE-5 WHERE id = ?";
Показалось, что так будет чуть более явно отображаться изменение рейтинга.
Изменил на +1 и -1

2023-03-14 16:59 UTC, Sunkerus commented on src/main/resources/schema.sql
> +    description  varchar(100),
Исправил, добавил символов для строки.

2023-03-14 17:14 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Допустил ошибку, случайно добавил лишнюю проверку.
Проверка уже происходит  на моменте добавления с помощью метода validateCorrect(user)
Исправил.

2023-03-14 17:24 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/genre/GenreDbStorage.java
> +    public void add(String genre) {
Также немного оишбся, добавил для функциональности, и возможности указания жанра и mpa.
Т.К. **по тз нет необходимости оставлять этот метод**, то логичнее будет его убрать.

2023-03-14 17:24 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/mpa/MpaDbStorage.java
> +    public void add(String mpa) {
Добавил для увеличения функциональности, но также не учел, что по ТЗ  такой задачи нет.

2023-03-14 18:59 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.containsFilm(id)) {
Добавил отслеживание, обновил схему работы бд

2023-03-15 16:53 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.getGenres().forEach(genre -> jdbcTemplate.update(sqlGenre, filmId, genre.getId()));
- Реализовал всё с помощью batchUpdate -> BatchPreparedStatementSetter.
- Вывел в отдельную функцию
- Добавил блок try catch для ошибок.

2023-03-15 16:53 UTC, Sunkerus commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.getGenres().forEach(
Реализовал

2023-03-15 20:43 UTC, Sunkerus commented
Александр, привет!
Учел все исправления и требования, обновил базу данных.
Можешь посмотреть на схеме, которую я также добавил, находится в файле shema.png

2023-03-16 07:53 UTC, alexache approved these changes

2023-03-16 08:48 UTC, merged